package com.example.aidevelop.agent.model;

public enum AgentFailureReason {
    NONE,
    PLAN_PARSE_ERROR,
    REFLECT_PARSE_ERROR,
    SELF_CHECK_FAILED,
    STRUCTURED_OUTPUT_INVALID,
    LLM_TIMEOUT,
    TOOL_TIMEOUT,
    TOOL_UNAUTHORIZED,
    TOOL_EXECUTION_FAILED,
    BUDGET_EXCEEDED,
    REPLAN_EXHAUSTED,
    SUPERVISOR_DECISION_ERROR,
    TRACE_PERSIST_FAILED,
    UNKNOWN
}
